DATASET:
  root_dataset: "C:/alon/AgriVision/"
  list_test: "./data/agri-test.odgt"
  list_train: ["./data/agri-trn.odgt"]
  list_val: "./data/agri-val.odgt"
  num_class: 7
  segm_downsampling_rate: 1.0

MODEL:
  arch: "deeplab"
  os: 16
  backbone: "resnet101"
  ibn_mode: "none"
  num_low_level_feat: 3

LOSS:
  bce: 1.0
  dice: 1.0
  lovasz: 1.0
  iou: 1.0

TRAIN:
  workers: 0

TEST:
  batch_size_per_gpu: 16
  #checkpoint: "pretrained/ibn101a-deeplab-lowfeat@3-aug.pth"
  checkpoint: "./pretrained/resnet101-5d3b4d8f.pth"
  result: "./result"

DIR: "ckpt/"
