model:
    arch: unet
    smooth_layers: 0
data:
    dataset: agrivision6
    train_split: train_small_2731
    val_split: val_small
    test_split: test
    img_rows: 512
    img_cols: 512
    n_channels: 5
    channel_vector: [1,1,1,1,1]
    path: C://alon/datasets/Agriculture-Vision/
training:
    train_iters: 10000
    val_interval: 50   # 200
    print_interval: 10  # 50
    batch_size: 8
    n_workers: 4
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        #momentum: 0.99
        #weight_decay: 0.0005
    loss:
        name: 'mean_iou_softmax'
        reduction: 'mean'
        ignore_index: 7
        weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]    
    lr_schedule:
        #step_size: 100
        #gamma: 0.1
    pretrained_model: None    # agrivision6_best_model_pretrained_0.pkl   
    augmentations:
        basic:
            saturation: 0.01    #[saturation varied in 1-x to 1+x]
            hue: 0.01           #[hue varied in -x to x]
            brightness: 0.01    #[brightness varied in 1-x to 1+x]
            gamma: 0.01         #[gamma varied in 1 to 1+x]
            contrast: 0.01      #[contrast varied in 1-x to 1+x]
            #ccrop: [h,w]       #[center crop of (h,w)]
            #rcrop: [10, 10]    #[crop of size (h,w)]
            rotate: 5           #[rotate -d to d degrees]
            scale: [0.99, 1.01] #[scale in range (s_min, s_max)]
            translate: [1, 1]   #[translation by max (du, dv)]
            hflip: 0.5          #[flip horizontally with chance p]
            #vflip: 0           #[flip vertically with chance p]
        collage:
            n_patches: 7
validation:
    image_dir: val_small
    out_dir: out1_val_small_E
debug_info:
    save_training_images: 0
    save_training_dir: runs/zz_debug_pics   
misc:
    run_dir: runs/tst3c_k5/t3
    saved_model: agrivision6_best_model.pkl
    random_seed: 1337
    