model:
    arch: unet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    test_split: test
    img_rows: 256
    img_cols: 512
    path: C://alon/datasets/cityscapes/
training:
    train_iters: 25000
    batch_size: 1
    val_interval: 20
    n_workers: 8
    print_interval: 5
    optimizer:
        name: 'adam'
        lr: 1.0e-3
    loss:
        name: 'cross_entropy'
        size_average: False
    l_rate: 1.0e-4
    lr_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
